# Generated by Django 5.1.1 on 2024-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olma_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='Karta raqami')),
                ('expiry_date', models.CharField(max_length=4, verbose_name='Amal qilish muddati (MMYY)')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism va familiya')),
            ],
        ),
    ]
